region: us-east-1
ecr_name: biosmesh-all-apps
dns_name: biosapplication.com
zone_id: Z1023527RS6FKHEBV4ZZ
vpc_id: vpc-08da13046fc0ea8fc
kms_name: mcp_bios_vault_auto_unseal
dynamodb_name: biosmesh-dynamodb-tflock-state

tags:
  Owner: Bios
  Developer: Farhaan
  Application: mcp-init
  Provisioner: Terraform
  Name: biosmesh-mcp-init
  Environment: production

load_balancers:
  global_dev_apps: global-dev-apps
  global_mcp_apps: global-mcp-apps

s3_buckets:
  vault: biosmesh-vault
  mcp: biosmesh-spot-plane
  tfstate: biosmesh-tf-state
  workers: biosmesh-apps-config

subnet_ids:
  - subnet-00559225548afa7d4
  - subnet-078d8ce666dcbd6ba
  - subnet-0c73f4d65aef7adf4
  - subnet-0e3597bed0f180f79
  - subnet-0d75bad323fdb2481
  - subnet-0c26209bd1cfeeac6

security_groups:
  global_mcp_apps:
    instance:
      ingress: [ ]
    alb:
      ingress:
        - to_port: 80
          from_port: 80
          protocol: tcp
          description: "HTTP from VPC"
          cidr_blocks:
            - "0.0.0.0/0"

        - to_port: 443
          from_port: 443
          protocol: tcp
          description: "TLS from VPC"
          cidr_blocks:
            - "0.0.0.0/0"

        - to_port: 9090
          from_port: 9090
          protocol: tcp
          description: "Prometheus Connection"
          cidr_blocks:
            - "0.0.0.0/0"

        - to_port: 9093
          from_port: 9093
          protocol: tcp
          description: "Nginx Exporter Connection"
          cidr_blocks:
            - "0.0.0.0/0"
  global_dev_apps:
    instance:
      ingress: [ ]
    alb:
      ingress:
        - to_port: 80
          from_port: 80
          protocol: tcp
          description: "HTTP from VPC"
          cidr_blocks:
            - "0.0.0.0/0"

        - to_port: 443
          from_port: 443
          protocol: tcp
          description: "TLS from VPC"
          cidr_blocks:
            - "0.0.0.0/0"

        - to_port: 27017
          from_port: 27017
          protocol: tcp
          description: "MongoDB Connections"
          cidr_blocks:
            - "0.0.0.0/0"

        - to_port: 3306
          from_port: 3306
          protocol: tcp
          description: "Mysql Connections"
          cidr_blocks:
            - "0.0.0.0/0"

        - to_port: 5432
          from_port: 5432
          protocol: tcp
          description: "Postgres Connections"
          cidr_blocks:
            - "0.0.0.0/0"

        - to_port: 6379
          from_port: 6379
          protocol: tcp
          description: "Redis Connections"
          cidr_blocks:
            - "0.0.0.0/0"
