apiVersion: 1

datasources:
  - orgId: 1
    access: proxy
    editable: true
    uid: prometheus
    isDefault: true
    basicAuth: false
    name: Prometheus
    type: prometheus
    url: http://prometheus:9090

  - orgId: 1
    uid: loki
    name: Loki
    type: loki
    access: proxy
    editable: true
    isDefault: false
    basicAuth: false
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '(?:traceID|trace_id)=(\w+)'
          name: TraceID
          url: $${__value.raw}

  - orgId: 1
    editable: true
    uid: cloudwatch
    isDefault: false
    name: CloudWatch
    type: cloudwatch
    jsonData:
      authType: default
      defaultRegion: us-east-1

  - orgId: 1
    uid: tempo
    name: Tempo
    type: tempo
    access: proxy
    editable: true
    basicAuth: false
    isDefault: false
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
