apiVersion: 1

datasources:
  - orgId: 1
    access: proxy
    editable: true
    uid: defaultPrometheus
    isDefault: true
    basicAuth: false
    name: Prometheus
    type: prometheus
    url: http://prometheus:9090

  - orgId: 1
    name: Loki
    type: loki
    access: proxy
    editable: true
    uid: defaultLoki
    isDefault: false
    basicAuth: false
    url: http://loki:3100
#    jsonData:
#      derivedFields:
#        - datasourceUid: tempo
#          matcherRegex: '(?:traceID|trace_id)=(\w+)'
#          name: TraceID
#          url: $${__value.raw}

  - name: Pyroscope
    type: pyroscope-datasource
    access: proxy
    orgId: 1
    uid: defaultPyroscope
    jsonData:
      path: http://pyroscope:4040

  - orgId: 1
    editable: true
    isDefault: false
    name: CloudWatch
    type: cloudwatch
    uid: defaultCloudwatch
    jsonData:
      authType: default
      defaultRegion: us-east-1

#  - orgId: 1
#    name: Tempo
#    type: tempo
#    access: proxy
#    editable: true
#    basicAuth: false
#    isDefault: false
#    uid: defaultTempo
#    url: http://tempo:3200
#    jsonData:
#      httpMethod: GET
#      serviceMap:
#        datasourceUid: prometheus
