pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    environment {
        aws_region="us-east-1"
        tear_down="${params.tear_down}"
        aws_profile_name="spot-platform"
        jenkins_filepath="tf_runner/api-lookup"
        ami_name = 'redflag-service-apilookup-packer-spot'
        s3_bucket_name="spot-platform/redflag-api-lookup-prod"
        def ami_id = sh(script: "aws ec2 describe-images --profile=${aws_profile_name} --region=\"$aws_region\" --filters '[{\"Name\": \"name\", \"Values\": [\"$ami_name\"]}]' | jq -r '.Images[0].ImageId'", returnStdout: true).trim()
    }

    stages {
        stage("Updating config file") {
            steps {
                script {
                    if ("${tear_down}" == "true") {
                    	sh """
	                    cd ${env.jenkins_filepath}
	                    contents="\$(jq '.spot_config.auto_scaling_group.desired_instances = 0 | .ami_id = "${env.ami_id}"' config.json)"
	                    echo \$contents > config.json
	                    """
                    }
                    else {
                        if ("${params.ami_id}" == "null"){
                            sh """
                            cd ${env.jenkins_filepath}
                            contents="\$(jq '.ami_id = "${env.ami_id}"' config.json)"
                            echo \$contents > config.json
                            """
                        }
                        else {
                            sh """
                            cd ${env.jenkins_filepath}
                            contents="\$(jq '.ami_id = "${params.ami_id}"' config.json)"
                            echo \$contents > config.json
                            """
                        }
                    }
                }
            }
        }

        stage("Pull TF state from S3") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    aws s3 cp "s3://${env.s3_bucket_name}/terraform.tfstate" ./tf_script --profile=${env.aws_profile_name} --region=${env.aws_region}
                    """
                }
            }
        }

        stage("Terraform Init") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform init
                    """
                }
            }
        }

        stage("Terraform Validate") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform validate
                    """
                }
            }
        }

        stage("Terraform Apply") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    export AWS_PROFILE=${env.aws_profile_name}
                    terraform apply -auto-approve
                    """
                }
            }
        }

        stage("Push TF state to S3") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    aws s3 cp ./tf_script/terraform.tfstate "s3://${s3_bucket_name}/" --profile=${aws_profile_name} --region=${env.aws_region}
                    """
                }
            }
        }
    }
}
