env: production
region: us-east-1
key_name: bios-new
ebs_volume_size: 8
app: mcp-deployment
s3fs_name: deployment
instance_type: t3.medium
ebs_multi_attach_volume_size: 20
private_key_name_path: bios-new.pem

availability_zones:
  - us-east-1a

od_config:
  instance_type:
    - t3.small
    - t3.medium
    - t3.large
  auto_scaling_group:
    min_instances: 0
    max_instances: 1
    desired_instances: 1

spot_config:
  instance_type:
    - t3.small
    - t3.medium
    - t3.large
  auto_scaling_group:
    min_instances: 0
    max_instances: 1
    desired_instances: 1

dns_names:
  - dns: "mcp.vault.biosapplication.com"
    port: 8200
    name: vault
  - dns: "mcp.deployment.biosapplication.com"
    port: 80
    name: jenkins

tags:
  Owner: Bios
  Developer: Farhaan
  Provisioner: Terraform
  Environment: production
  Application: mcp-deployment
  Name: biosmesh-mcp-deployment
