env: production
region: us-east-1
key_name: bios-new
app: mcp-deployment
instance_type: t3.medium
private_key_name_path: bios-new.pem

dns_names:
  - dns: "mcp.vault.biosapplication.com"
    port: 8200
    name: vault
  - dns: "mcp.deployment.biosapplication.com"
    port: 80
    name: jenkins

tags:
  Owner: Bios
  Developer: Farhaan
  Provisioner: Terraform
  Environment: production
  Application: mcp-deployment
  Name: biosmesh-mcp-deployment
