user  nginx;
worker_processes  auto;

error_log  /dev/stdout;
pid        /var/run/nginx.pid;


events {
    worker_connections  5120;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  json  '{'
                 '"time": "$time_iso8601", '
                 '"remote_addr": "$remote_addr", '
                 '"request": "$request", '
                 '"status": "$status", '
                 '"bytes_sent": "$body_bytes_sent", '
                 '"referer": "$http_referer", '
                 '"user_agent": "$http_user_agent"'
                 '}';

    access_log /dev/stdout json;

    sendfile        on;
    keepalive_timeout  100;
    include /etc/nginx/conf.d/*.conf;
}
