env: production
region: us-east-1
key_name: bios-new
app: mcp-observability
instance_type: a1.medium
zone_name: ***REMOVED***
private_key_name_path: bios-new.pem
dns_name: mcp.observability.***REMOVED***
global_dev_mcp_load_balancer_name: global-mcp-apps-us-east-1

tags:
  Owner: Bios
  Developer: Farhaan
  Provisioner: Terraform
  Environment: production
  Application: mcp-observability
  Name: biosmesh-mcp-observability
