env: production
region: us-east-1
key_name: bios-new
app: mcp-observability
instance_type: a1.medium
private_key_name_path: bios-new.pem
dns_name: mcp.observability.biosapplication.com
global_zone_name_1: biosapplication.com

tags:
  Owner: Bios
  Developer: Farhaan
  Provisioner: Terraform
  Environment: production
  Application: mcp-observability
  Name: biosmesh-mcp-observability

s3_buckets:
  mcp: biosmesh-spot-plane
