app: mcp
env: development
region: us-east-1
key_name: bios-new
instance_type: c5a.large
ami_id: ami-09e67e426f25ce0d7
zone_id: Z1023527RS6FKHEBV4ZZ
vpc_id: vpc-08da13046fc0ea8fc
name: monitoring-control-plane
lb_algorithm_type: round_robin
dns_name: mcp.***REMOVED***
private_key_name_path: bios-new.pem

tags:
  Owner: Bios
  Application: mcp
  Name: biosmesh-mcp
  Developer: Farhaan
  Provisioner: Terraform
  Environment: development

subnet_ids:
  - subnet-00559225548afa7d4
  - subnet-078d8ce666dcbd6ba
  - subnet-0c73f4d65aef7adf4
  - subnet-0e3597bed0f180f79
  - subnet-0d75bad323fdb2481
  - subnet-0c26209bd1cfeeac6
