version: 0.0

os: linux
files:
  - source: /
    destination: /home/ubuntu/backend-webapp

hooks:
  BeforeInstall:
    - location: deployment_scripts/cleanup.sh
      timeout: 100
      runas: root

  AfterInstall:
    - location: deployment_scripts/deploy_app.sh
      timeout: 300
      runas: root
