env: production
region: us-east-1
key_name: bios-new
app: mcp-deployment
instance_type: t2.medium
zone_name: biosapplication.com # mcp
private_key_name_path: bios-new.pem
dns_name_vault: mcp.vault.biosapplication.com
dns_name_jenkins: mcp.deployment.biosapplication.com
global_dev_mcp_load_balancer_name: global-mcp-apps-us-east-1 # mcp

tags:
  Owner: Bios
  Developer: Farhaan
  Provisioner: Terraform
  Environment: production
  Application: mcp-deployment
  Name: biosmesh-mcp-deployment
