env: production
region: us-east-1
key_name: bios-new
app: mcp-observability
instance_type: a1.medium
zone_name: ***REMOVED***
private_key_name_path: bios-new.pem
dns_name: mcp.observability.***REMOVED***
global_dev_mcp_load_balancer_arn: "arn:aws:elasticloadbalancing:us-east-1:***REMOVED***:loadbalancer/app/global-mcp-apps-us-east-1/5d2b1ac8971f186a"

tags:
  Owner: Bios
  Name: biosmesh-mcp
  Developer: Farhaan
  Provisioner: Terraform
  Environment: production
  Application: mcp-observability
