env: production
region: us-east-1
key_name: bios-new
app: mcp-deployment
instance_type: t2.medium
zone_name: ***REMOVED***
private_key_name_path: bios-new.pem
dns_name_vault: mcp.vault.***REMOVED***
dns_name_jenkins: mcp.deployment.***REMOVED***
global_dev_mcp_load_balancer_arn: "arn:aws:elasticloadbalancing:us-east-1:***REMOVED***:loadbalancer/app/global-mcp-apps-us-east-1/5d2b1ac8971f186a"

tags:
  Owner: Bios
  Developer: Farhaan
  Provisioner: Terraform
  Environment: production
  Application: mcp-deployment
  Name: biosmesh-mcp-deployment
