version: "3.8"

networks:
  spotops_deployment:

services:
  vault-server:
    image: vault:latest
    restart: always
    container_name: vault-server
    volumes:
      - ./config:/vault/config
    ports:
      - "8200:8200"
    environment:
      - "VAULT_ADDR=http://127.0.0.1:8200"
      - "VAULT_ADDRESS=http://127.0.0.1:8200"
      - "VAULT_API_ADDR=http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - spotops_deployment
    command: vault server -config=/vault/config/vault_config.json

  vault-ops:
    build:
      context: unseal_sidecar
      dockerfile: Dockerfile
    container_name: vault-ops
    user: root
    environment:
      - "S3_VAULT_BUCKET=biosmesh-vault"
      - "VAULT_ADDRESS=http://vault-server:8200"
      - "VAULT_CONFIG_FILE=/config/vault_config.json"
      - "S3_VAULT_FILENAME=internal_vault_config/keys.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/vault_config.json:/config/vault_config.json
    depends_on:
      - vault-server
    networks:
      - spotops_deployment
