Recovery Key 1: QG9l5E4acw17NhI3Q8PQO2PFsFUXe0iRq4QFh/DAjQnz
Recovery Key 2: nP6jRTqyUuGrgaItXBC8lYZKJXlUPI4+YoDXKo67HZdo
Recovery Key 3: bHKtvdaL+JLfNoU+5Y1g+6IPAK5uSAxzN1pGO7Wu9a0e
Recovery Key 4: eirrcGorzWCMECwCDmLy+YYdgyBcJOyOISy1PtPDxcns
Recovery Key 5: kzIGirNNlOFv9qJvGTH9AF1kGv5GcSQELiBksY7j/loE

Initial Root Token: hvs.aMsxmAYwYrr4OeZaI7FmX4MN

Success! Vault is initialized
