{
 "title": "Platform Monitoring",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({application=~\"$application\"},environment)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({application=~\"$application\", environment=~\"$environment\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "NIC",
    "query": {
     "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes (Cluster)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{application=~\"$application\", environment=~\"$environment\"})"
    }
   ]
  },
  {
   "title": "Current Container Image Tag",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_tasks_state{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\", container_label_com_docker_compose_service=\"main_application\"}) by (image)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{application=~\"$application\", environment=~\"$environment\", mode='system'})"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{application=~\"$application\", environment=~\"$environment\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\"} - node_memory_MemFree_bytes{application=~\"$application\", environment=~\"$environment\"} - (node_memory_Cached_bytes{application=~\"$application\", environment=~\"$environment\"} + node_memory_Buffers_bytes{application=~\"$application\", environment=~\"$environment\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{application=~\"$application\", environment=~\"$environment\", fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"})"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{application=~\"$application\", environment=~\"$environment\", mountpoint=\"/\"} - node_filesystem_free_bytes{application=~\"$application\", environment=~\"$environment\", mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[2m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - node_memory_MemFree_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - (node_memory_Cached_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} + node_memory_Buffers_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance)(node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - node_memory_MemFree_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - (node_memory_Cached_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} + node_memory_Buffers_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network RX/TX Total (bytes/sec)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\", device=~\"$device\"}[2m])) + sum(rate(node_network_receive_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\", device=~\"$device\"}[2m])) "
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_transmit_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\", device=~\"$device\"}[5m]))",
     "legendFormat": "TX : {{ instance }}"
    },
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\", device=~\"$device\"}[5m]))",
     "legendFormat": "RX : {{ instance }}"
    }
   ]
  },
  {
   "title": "Server Resource Overview",
   "type": "table-old",
   "description": "\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{application=~\"$application\", environment=~\"$environment\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{oapplication=~\"$application\", environment=~\"$environment\"}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{application=~\"$application\", environment=~\"$environment\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{oapplication=~\"$application\", environment=~\"$environment\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{application=~\"$application\", environment=~\"$environment\"} / (node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{application=~\"$application\", environment=~\"$environment\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{application=~\"$application\", environment=~\"$environment\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {application=~\"$application\", environment=~\"$environment\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{application=~\"$application\", environment=~\"$environment\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{application=~\"$application\", environment=~\"$environment\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{application=~\"$application\", environment=~\"$environment\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{application=~\"$application\", environment=~\"$environment\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_filesystem_size_bytes {application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\"}-0",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "node_filesystem_avail_bytes {application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "分区使用率"
    }
   ]
  }
 ]
}