global_dev_apps_lb_arn: arn:aws:elasticloadbalancing:us-east-1:***REMOVED***:loadbalancer/app/global-dev-apps-us-east-1/10aa052609edd2f3
global_dev_apps_lb_security_group_id: sg-0d3f3890e1303f82b
global_mcp_apps_lb_arn: arn:aws:elasticloadbalancing:us-east-1:***REMOVED***:loadbalancer/app/global-landscape-apps-us-east-1/6767a1b0542a4146
global_mcp_apps_lb_security_group_id: sg-0d93f2bde87dbfa92
global_zone_name_1: ***REMOVED***
mcp_ecr_id: ***REMOVED***.dkr.ecr.us-east-1.amazonaws.com/biosmesh-all-apps
s3_mcp_spot_plane_bucket_name: biosmesh-spot-plane
s3_mcp_tfstate_bucket_name: biosmesh-tf-state
s3_mcp_vault_bucket_name: biosmesh-vault
s3_mcp_worker_bucket_name: biosmesh-apps-config
tfstate_dynamodb_name: biosmesh-dynamodb-tflock-state
vault_kms_id: de6cf55b-3c3c-4a08-a19d-8c3f626ef023
