server {
    listen        9999;
    server_name   _;

   location /internal/spotops/health {
        access_log off;

        add_header 'Content-Type' 'application/json';
        return 200 '{"status":"Healthy"}';
    }
}