name: backend
tcpApp: false
appType: public

tags:
  Owner: Bios
  MCP_SD: true
  Platform: biosmesh
  Provisioner: Terraform

routing:
  - dnsName: development.biosapplication.com
    httpsRedirect: false
    servicePorts:
      - externalPort: 80
        internalPort: 8000
    rateLimit:
      rate: 10/s
      burst: 0
      nodelay: true

deployment:
  baseDiskSize: 8
  replicaPerHost: -1
  AWSPolicyArn: null
  statefulset: false
  nodePreference: spot
  personalCluster: false
  imageRegistry: internal
  environment: development
  version: development-backend-77d71e132ebfde0ad8f437a6522f9d75a7d5f8fc
  extraConfig:
    commands: [ ]

  resources:
    limit:
      cpu: 10
      memory: 16Gi

  instanceType:
    - t3.small
    - t3.medium
    - t3.large

  autoScalingGroup:
    minInstances: 0
    maxInstances: 1
    desiredInstances: 1


  livenessProbe:
    httpGet:
      port: 8080
      path: /healthcheck
    initialDelaySeconds: 20
    periodSeconds: 10
