server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: '${LOKI_URL}'

scrape_configs:
  - job_name: jenkins-runners
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /build_logs/*.log
          application: jenkins-runners
          environment: '${ENVIRONMENT}'
    relabel_configs:
      - source_labels: [ '__path__' ]
        regex: '.*/(.*)'
        target_label: 'job_name'
        action: keep
      - source_labels: [ filename ]
        regex: '^(.*)\.log$'
        target_label: 'job_name'
