version: "3.8"

networks:
  spotops_deployment:


x-logging:
  &default-logging
  driver: loki
  options:
    keep-file: "false"
    loki-url: https://mcp.observability.biosapplication.com/loki/api/v1/push
    loki-external-labels: "instance=mcp,application=mcp-deployment,environment=production,container_name={{.Name}}"


services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    logging: *default-logging
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
    networks:
      - spotops_deployment


volumes:
  minio_storage:
