pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    environment {
        aws_region="us-east-1"
        aws_profile_name="spot-platform"
        ami_name = 'spot-platform-custom-backed-ami'
        def image_id = sh(script: "aws ec2 describe-images --profile=${env.aws_profile_name} --region=\"$aws_region\" --filters '[{\"Name\": \"name\", \"Values\": [\"$ami_name\"]}]' | jq -r '.Images[0].ImageId'", returnStdout: true).trim()
        def snapshot_id = sh(script: "aws ec2 describe-images --profile=${env.aws_profile_name} --region=\"$aws_region\" --filters '[{\"Name\": \"name\", \"Values\": [\"$ami_name\"]}]' | jq -r '.Images[0].BlockDeviceMappings[0].Ebs.SnapshotId'", returnStdout: true).trim()
    }

    stages {
        stage("Building Docker Image") {
            steps {
                script {
                    sh """
                        docker build .
                    """
                }
            }
        }

        stage("Push Image to ECR") {
            steps {
                script {
                    sh """
                        cd custom_baked_ami/
                        packer init .
                    """
                }
            }
        }
    }

    post {
        success {
            script {
                if ("${env.image_id}" != "null") {
                    sh """
                    echo "Deleting AMI image: ${env.image_id}"
                    aws ec2 deregister-image --profile=${env.aws_profile_name} --region=${env.aws_region} --image-id='${env.image_id}-old'
                    """
                }
                if ("${env.snapshot_id}" != "null") {
                    sh """
                    echo "Deleting Snapshot: ${env.snapshot_id}"
                    aws ec2 delete-snapshot --profile=${env.aws_profile_name} --region=${env.aws_region} --snapshot-id=${env.snapshot_id}
                    """
                }
            }
        }

        failure {
            script {
                if (env.image_id != "null") {
                    sh """
                        aws ec2 create-tags  --resources ${env.image_id} --tags Key=Name,Value=${env.ami_name} --profile=${env.aws_profile_name} --region=${env.aws_region}
                    """
                }
            }
        }
    }
}
