pipeline {
    agent any

    stages {
        stage("Scaling Application") {
            steps {
                script {
                    sh """
                    cd /auto_scaler
                    . venv/bin/activate
                    python3 run.py
                    """
                }
            }
        }
    }
}
