version: "3.8"

networks:
  spotops_monitoring:

services:
  s3fs:
#    pid: "host"
    privileged: true
    restart: on-failure
    tty: true
    container_name: s3fs
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spotops_monitoring
    environment:
      - "application=deployment"
      - "bucket_name=biosmesh-spot-plane"
    volumes:
      - /mnt:/mnt

  testing_application:
    image: ubuntu:latest
    container_name: s3fs_testing_app
    tty: true
    restart: always
    volumes:
      - /mnt:/mnt
    networks:
      - spotops_monitoring
