variable "app" {}
variable "env" {}
variable "tags" {}
variable "name" {}
variable "region" {}
variable "key_name" {}
variable "zone_name" {}
variable "instance_type" {}
variable "regional_name" {}
variable "dns_name_vault" {}
variable "dns_name_jenkins" {}
variable "private_key_name_path" {}
variable "global_dev_mcp_load_balancer_name" {}
